# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Asksolr < Formula
  desc "Agentic Apache Solr CLI — query Solr in plain English using Claude."
  homepage "https://github.com/CodeYogiCo/asksolr"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CodeYogiCo/asksolr/releases/download/v0.1.0/asksolr_0.1.0_darwin_amd64.tar.gz"
      sha256 "1749ee4d7db42a28d35c8881989493d45420a7b456e9782c8f0430d279be6024"

      define_method(:install) do
        bin.install "asksolr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CodeYogiCo/asksolr/releases/download/v0.1.0/asksolr_0.1.0_darwin_arm64.tar.gz"
      sha256 "397441c987ab839e05545955372744bc9471a71a4d95809b135d490e7330adaf"

      define_method(:install) do
        bin.install "asksolr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CodeYogiCo/asksolr/releases/download/v0.1.0/asksolr_0.1.0_linux_amd64.tar.gz"
      sha256 "20c40688a7d92b7cd43cce9d22510c50e1bc317ecf3cbb242cc6d95af432d7b4"
      define_method(:install) do
        bin.install "asksolr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CodeYogiCo/asksolr/releases/download/v0.1.0/asksolr_0.1.0_linux_arm64.tar.gz"
      sha256 "685a80627f2866b08922a13d8d12175dfb31499ecbd93a6ff1798659251b30ab"
      define_method(:install) do
        bin.install "asksolr"
      end
    end
  end

  test do
    system "#{bin}/asksolr", "--help"
  end
end
